### ISSUE TITLE
bug pour effacer les roles

### ISSUE THREAD

**Issue by kylian0000** [JacqueSatan/Discord-bot#16]
erreur 1 : Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\KYLIAN VIDEO\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\KYLIAN VIDEO\Downloads\Discord-bot-1.4.5b (1)\Discord-bot-1.4.5b\core\individuals\roles.py", line 73, in <lambda>
    vl = Button(all, text="Valider et lancer l'attaque", width=50, command=lambda:lancer(eav, oav, env, srv, crv))
  File "C:\Users\KYLIAN VIDEO\Downloads\Discord-bot-1.4.5b (1)\Discord-bot-1.4.5b\core\individuals\roles.py", line 65, in lancer
    data["roles"]["code"]["eadmin"] = eav.get()
KeyError: 'roles'

erreur 2 : (node:8080) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DiscordAPIError: Missing Permissions

windows 10
version de python : 3.7

**Comment by iarios** [comment]
Et le bot peut supprimer les roles qui ont un cadenas ? Personne dans mon serveur ne peut les supprimer ou les modifier, meme pas l'admin.

**Comment by iarios** [comment]
J'ai lu dans un precedent post que vous avez arreter le developpement, c'est definitif ou il est possible de le reprendre ?

**Comment by JacqueSatan** [comment]
c'est définitif, du moins pour cette application si, une autre plus fiable, plus simple d'utilisation est en développement.
